ktor:
  application:
    modules:
      - com.inventy.ApplicationKt.module
  deployment:
    port: 8080

database:
  embedded:  $EMBEDDED
  url: 'jdbc:postgresql://localhost:5432/inventy'
  driver: org.postgresql.Driver
  user: inventy
  password: inventy

barcode-lookup:
  api-key: jbquizcvk482qox1cfxrjcqsbawnob

auth0:
  issuer: 'https://damoad.eu.auth0.com/'
  audience: inventy-backend