ktor:
  application:
    modules:
      - com.inventy.ApplicationKt.module
  deployment:
    port: 8080
    maxInitialLineLength: 2048
    maxHeaderSize: 1024
    maxChunkSize: 42

database:
  embedded: false
  host: ${DB_HOST}
  port: ${DB_PORT}
  databaseName: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}

barcode-lookup:
  api-key: jbquizcvk482qox1cfxrjcqsbawnob

auth0:
  issuer: 'https://damoad.eu.auth0.com/'
  audience: inventy-backend