ktor:
  application:
    modules:
      - com.inventy.ApplicationKt.module
  deployment:
    port: 8080
    maxInitialLineLength: 2048
    maxHeaderSize: 1024
    maxChunkSize: 42

database:
  embedded: false
  host: localhost
  port: 5432
  databaseName: inventy
  user: inventy
  password: inventy

barcode-lookup:
  api-key: jbquizcvk482qox1cfxrjcqsbawnob

auth0:
  issuer: 'https://damoad.eu.auth0.com/'
  audience: inventy-backend